# Generated by Django 3.1.6 on 2021-02-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210217_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='Product'),
            preserve_default=False,
        ),
    ]
